name: CI/CD Deploy to EC2

on:
  push:
    branches:
      - main   # branch muốn deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Copy SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ci-cd-key
          chmod 600 ~/.ssh/ci-cd-key

      - name: Add server to known hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/ci-cd-key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            echo "Deploying project..."

            # Project root chứa .git
            cd ${{ secrets.PROJECT_DIR }}
            git reset --hard
            git pull origin main

            # List các service cần deploy
            services=("sso-server" "content-server")

            for service in "${services[@]}"
            do
              echo "Deploying $service..."
              cd ${{ secrets.PROJECT_DIR }}/$service
              npm install
              npm run build
              pm2 restart $service || pm2 start dist/main.js --name $service
            done

            echo "Deployment finished!"
          EOF
